name: Release to 13337 reservoir nodes
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**

run-name: ${{ github.workflow }} by @${{ github.actor }} from ${{ github.ref_name }}

jobs:
  release-to-13337-reservoir-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Reload reservoir processes on all nodes
        uses: ./.github/actions/remote-commands
        with:
          ssh-host: ${{ secrets.HOST_PROD }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVKEY }}
          ssh-port: ${{ secrets.SSH_PORT }}
          ssh-command: |
            ansible-playbook /home/ubuntu/playbooks/release.yml -l 13337-reservoir-main

  release-to-13337-reservoir-read-01:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Reload reservoir processes on all nodes
        uses: ./.github/actions/remote-commands
        with:
          ssh-host: ${{ secrets.HOST_PROD }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVKEY }}
          ssh-port: ${{ secrets.SSH_PORT }}
          ssh-command: |
            ansible-playbook /home/ubuntu/playbooks/release.yml -l 13337-reservoir-read-01
