name: Release to 13473 zkevm-testnet nodes
on:
  workflow_dispatch:

run-name: ${{ github.workflow }} by @${{ github.actor }} from ${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodes:
          - zkevm-testnet-reservoir-main
          - zkevm-testnet-reservoir-read-01
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Reload reservoir processes on all nodes
        uses: ./.github/actions/remote-commands
        with:
          ssh-host: ${{ secrets.HOST_PROD }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVKEY }}
          ssh-port: ${{ secrets.SSH_PORT }}
          ssh-command: |
            ansible-playbook -v /home/ubuntu/playbooks/release.yml -l ${{ matrix.nodes }}
