name: Release to all reservoir nodes
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**

run-name: ${{ github.workflow }} by @${{ github.actor }} from ${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodes:
          - 13337-reservoir-main
          - 13337-reservoir-read-01
          - zkevm-testnet-reservoir-main
          - zkevm-testnet-reservoir-read-01
          - beam-reservoir-test-acceu
          - beam-reservoir-test-acceu-readonly
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Reload reservoir processes on all nodes
        uses: ./.github/actions/remote-commands
        with:
          ssh-host: ${{ secrets.HOST_PROD }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVKEY }}
          ssh-port: ${{ secrets.SSH_PORT }}
          ssh-command: |
            ansible-playbook -v /home/ubuntu/playbooks/release.yml -l ${{ matrix.nodes }}
