name: Release to 13337 reservoir nodes

on:
  workflow_dispatch:

run-name: ${{ github.workflow }} by @${{ github.actor }} from ${{ github.ref_name }}


jobs:
  release-to-13337-reservoir-main:
    runs-on: ubuntu-latest
    environment: Production
    env:
      SSH_JUMPHOST: ${{ secrets.SSH_JUMPHOST }}
      SSH_JUMP_USERNAME: ${{ secrets.SSH_JUMP_USERNAME }}
      SSH_JUMP_PORT: ${{ secrets.SSH_JUMP_PORT }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
    strategy:
      matrix:
        node: [BEAM_13337_RESERVOIR_MAIN, BEAM_13337_RESERVOIR_SECONDARY]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH keys
        uses: ./.github/actions/load-private-key
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVKEY }}

      - name: Load remote host keys
        uses: ./.github/actions/populate-known-hosts
        with:
          ssh-jump-host: ${{ secrets.SSH_JUMPHOST }}
          ssh-jump-username: ${{ secrets.SSH_JUMP_USERNAME }}
          ssh-jump-port: ${{ secrets.SSH_JUMP_PORT }}

          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-host: ${{ secrets[matrix.node] }}

      - name: Get working commit hash
        id: get-commit-hash
        uses: ./.github/actions/send-remote-commands
        with:
          ssh-jump-host: ${{ secrets.SSH_JUMPHOST }}
          ssh-jump-username: ${{ secrets.SSH_JUMP_USERNAME }}
          ssh-jump-port: ${{ secrets.SSH_JUMP_PORT }}

          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-host: ${{ secrets[matrix.node] }}
          ssh-command: sudo git -C /home/ubuntu/beam-reservoir rev-parse origin/main

      - name: Execute deployment steps
        id: execute-deployment
        uses: ./.github/actions/send-remote-commands
        with:
          ssh-jump-host: ${{ secrets.SSH_JUMPHOST }}
          ssh-jump-username: ${{ secrets.SSH_JUMP_USERNAME }}
          ssh-jump-port: ${{ secrets.SSH_JUMP_PORT }}

          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-host: ${{ secrets[matrix.node] }}
          ssh-command: |
            sudo systemctl stop reservoir
            sudo git -C /home/ubuntu/beam-reservoir pull origin main
            cd /home/ubuntu/beam-reservoir
            sudo git checkout main
            sudo yarn && sudo yarn build
            sudo systemctl start reservoir

      - name: Revert on failure
        if: failure() && steps.execute-deployment.outcome == 'failure'
        uses: ./.github/actions/send-remote-commands
        with:
          ssh-jump-host: ${{ secrets.SSH_JUMPHOST }}
          ssh-jump-username: ${{ secrets.SSH_JUMP_USERNAME }}
          ssh-jump-port: ${{ secrets.SSH_JUMP_PORT }}

          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-host: ${{ secrets[matrix.node] }}
          ssh-command: |
            sudo systemctl stop reservoir
            sudo git -C /home/ubuntu/beam-reservoir reset --hard ${{ steps.get-commit-hash.outputs.result }}
            cd /home/ubuntu/beam-reservoir
            sugo yarn && sudo yarn build
            sudo systemctl start reservoir
