name: Reload Reservoir processes
on:
  workflow_dispatch:

jobs:
  ansible-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Reload reservoir processes on all nodes
        uses: ./.github/actions/remote-commands
        with:
          ssh-host: ${{ secrets.HOST_PROD }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVKEY }}
          ssh-port: ${{ secrets.SSH_PORT }}
          ssh-command: |
            ansible -m shell -a "sudo systemctl restart reservoir" reservoir
